### ISSUE TITLE
Sound continually shutters on every game, RPi3

### ISSUE THREAD

**Issue by backstander** [libretro/beetle-pcfx-libretro#17]
I just rebuilt lr-beetle-pcfx (mednafen_pcfx_libretro.so) from source on RetroPie about an hour ago and every game runs at about 85% of full speed with continual shuttering sound.  I have the correct pcfx.rom file with the SHA1: 1a77fd83e337f906aecab27a1604db064cf10074.  Any more information you need from me, please let me know.

**Comment by twinaphex** [comment]
your Raspberry Pi 3 has no chance of running this at fullspeed.

It runs only at 'just' 150fps unthrottled on a Core i5 laptop PC. Your Raspberry Pi 3 is even weaker than a PS3, so not much hope there.

**Comment by backstander** [comment]
Thanks twinaphex for the info.  That's what I was worried would be the issue.  I was just hoping there was some optimization for ARM because it feels like it is almost there.

**Comment by RobLoach** [comment]
Aside from tweaking some of the video settings, there isn't much you can do on a RPi3 to improve performance.

This issue could likely be closed.
