### ISSUE TITLE
gcc build error on some Linux systems

### ISSUE THREAD

**Issue by Zombie-Ryushu** [libretro/beetle-pcfx-libretro#23]
libretro-common/rthreads/rthreads.o: In function `scond_wait_timeout':
/builddir/build/BUILD/libretro-20170303/libretro-mednafen_pcfx/libretro-common/rthreads/rthreads.c:457: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status

**Comment by Zombie-Ryushu** [comment]
I am using gccc 4.7.4 on a Rosa Linux 2012.1 System. On Rosa 2014.1 the module builds fine. But that has gcc 4.9.x

**Comment by retro-wertz** [comment]
you are probably using old compiler modules then.

**Comment by Zombie-Ryushu** [comment]
Are there any work arounds?
