### ISSUE TITLE
BIOS file name documentation

### ISSUE THREAD

**Issue by hooby3dfx** [libretro/beetle-pcfx-libretro#24]
Unless I'm missing something the docs say that the BIOS file should be named pcfx.rom, but it appears that it must be pcfx.bios.

**Comment by hizzlekizzle** [comment]
Good catch. Libretro.cpp seems to have two conflicting takes on it:
https://github.com/libretro/beetle-pcfx-libretro/blob/master/libretro.cpp#L431
and
https://github.com/libretro/beetle-pcfx-libretro/blob/master/libretro.cpp#L988

**Comment by retro-wertz** [comment]
pcfx.bios is the config name to read from, pcfx.rom is the actual bios from

https://github.com/libretro/beetle-pcfx-libretro/blob/master/mednafen/settings.cpp#L114

**Comment by retro-wertz** [comment]
bios config name (pcfx.bios) and the actual bios filename (pcfx.rom) should be clear by now....

**Comment by hooby3dfx** [comment]
Sorry, this was my bad!
