### ISSUE TITLE
CHD support for PC-FX

### ISSUE THREAD

**Issue by ajshell1** [libretro/beetle-pcfx-libretro#26]
This is a follow-up to a previous bounty.

All I ask is that someone adds CHD support to the Mednafen PC-FX Core.

I figured I might as well make a bounty for the last Mednafen core that uses CDs (other than the PSX, which I've been informed would be problematic).

I doubt many people are going to use it, but I think it would be a good feature to add. Hell, this is more of a "Give rtissera money" type thing.

This will have a bounty of $10.

**Comment by rtissera** [comment]
PR https://github.com/libretro/beetle-pcfx-libretro/pull/27

**Comment by ajshell1** [comment]
I'm encountering no issues with the latest build.

Chip Chan Kick, the translated version of Zeroigar, Kishin Kouji Zenki FX - Vajura Fight, and hte partially translated version of Ruruli Ra Rura all work in CHD format.

Pia Carrot's English translation doesn't work. However, I've discovered that this is because the bin/cue version I used to make the CHD doesn't work with RetroArch or standalone Mednafen. As soon as I manage to fix Pia-Carrot for testing  I'll be willing to award you the bounty. Let me know when you are satisfied with your work.

**Comment by rtissera** [comment]
@ajshell1 No rush for awarding the bounty, I do prefer to make sure other people validate it is working right before considering it "done".
The current implementation is shared between PCFX / PCE Fast / Saturn, once I have this single implementation on all three cores working okay I think we can consider it stable enough to move on PSX which will requires extra work.

**Comment by retro-wertz** [comment]
QUICK initial test:

Pia Carrot He Youkoso (English Translation) seems to work and loads fine(havent played much yet) aside from the leadout. This abruptly cuts-off the last portions of the the last track (Track 5 of Pia Carrot in the music player)

a quick test is to play Track 5 of the CD and listening to the last part of the song. using the bios' cd menu( upper-left icon) on the bios menu screen. 
![2](https://user-images.githubusercontent.com/23315382/29094189-0d7c8a6c-7cbf-11e7-842b-0deee7ba7b7e.jpg)

for comparison, here is pcfx log compared to pcfx source' gamedb(located in /mednafen/pcfx/gamedb.inc)
![1](https://user-images.githubusercontent.com/23315382/29094087-a2ed28f0-7cbe-11e7-965a-baef2bc14b80.jpg)

note: source cue file is tested here and track 5 ends normally as expected.

**Comment by rtissera** [comment]
PR #65 fixes the wrong leadout value.
Regarding @retro-wertz issues we discussed it on IRC, CHDMAN 0.146 is buggy and should not be used, I have confirmed it does not handle pregap properly and therefore the generated CHD is bad.

Please refrain from using CHDMAN 0.146 (just use the one from latest MAME mainline) and make sure to make other users aware of the issue.

**Comment by retro-wertz** [comment]
this should be working now.

**Comment by anothername99** [comment]
I don't have a lot of games, but the ones I tried seem to work fine. I approve.

**Comment by rtissera** [comment]
Can we consider this done ?

**Comment by twinaphex** [comment]
I will close it for you.
