### ISSUE TITLE
It doesn't compile anymore on PS3

### ISSUE THREAD

**Issue by Ezio-PS** [libretro/beetle-pcfx-libretro#30]
The core doesn't compile anymore on PS3, though it compiled and worked correctly untill some time ago (months).
Here's a log of the error while compiling it. [https://pastebin.com/PdZhCaxa](url)

**Comment by bparker06** [comment]
Just tried it on the buildbot and it works: http://p.0bl.net/29068

**Comment by bparker06** [comment]
This may be related to the changes @albertofustinoni has been making, but I'm not sure why your build cannot find the function definitions.

**Comment by Ezio-PS** [comment]
I get that error using older sdk than the one used by the buildbot. I switched to the one used by buildbot and i don't get compile issues. Anway i already know that a higher version of sdk generates a general state of freeze at the frontend and at the cores, with cores that don't work like they should.
I'll try however this core i get with higher sdk, tbh i have the same issue with wonderswan core, but i don't think i'll be lucky with it.
