### ISSUE TITLE
Saving doesn't work

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/beetle-pcfx-libretro#40]
Save states work but not standard saving in games.

Win7 x64, latest RA + core.

**Comment by retro-wertz** [comment]
confirmed here using Archlinux... from what i see, pc-fx is using fileio for savefile. looks like somewhere in these commits broke game save for the core:

https://github.com/libretro/beetle-pcfx-libretro/commit/82038c34f3dab48237cf9626df9cab0fe5255966
note: you need to compile after 2 Update commits though to successfully compile.

@twinaphex @albertofustinoni @claudiuslollarius

**Comment by retro-wertz** [comment]
this should be fixed in latest commit and being it now a libretro API, is able to save whenever a change in sram is detected.

**Comment by Tatsuya79** [comment]
Working now.
.sav to .srm seems to be working too.
