### ISSUE TITLE
Android not working

### ISSUE THREAD

**Issue by brunobelo** [libretro/beetle-pcfx-libretro#56]
This core won't work on android, black screen in all games. The same games works on windows. I'm using the same bios on windows and android, windows is working, android isn't.

I've tested on Shield TV, Moto Z2 Force, Moto Z Force, Much W1 and Nexus 4, various android versions, none working. :(

**Comment by thekiefs** [comment]
Same problem here

**Comment by negativeExponent** [comment]
no problems here:
https://forums.libretro.com/t/mednafen-pc-fx/23769/9?u=negativeexponent

**Comment by thekiefs** [comment]
I think the problem resides in the .zip function, for whatever reason. After unzipping, I can get it to load. I filed a bug report here: https://github.com/libretro/RetroArch/issues/10630

**Comment by negativeExponent** [comment]
there are better way to run cd-based games in a much more streamable compressed format like CHD. there is no reason and a waste or time and space to use compression that was not meant to be streamable.
