### ISSUE TITLE
CHDs crash the emulator

### ISSUE THREAD

**Issue by Sterophonick** [libretro/beetle-pcfx-libretro#67]
When running a game in CHD format, after the PC-FX boot screen, Retroarch crashes.
The emulator says it can accept CHD images, in the information screen.
Why does this happen?

**Comment by negativeExponent** [comment]
what system. try with latest commit

**Comment by LibretroAdmin** [comment]
I'm going to assume this is no longer an issue going by how long ago the issue was posted. If it still happens, post it again and we'll do something about it this time.
