### ISSUE TITLE
Problem on Wii

### ISSUE THREAD

**Issue by Edu789** [libretro/beetle-pcfx-libretro#76]
The PC-FX works very slowly...

**Comment by twinaphex** [comment]
I think this is more a general performance issue on the Wii. Not sue to what degree things can be optimized given the Wii's low performance specs.

**Comment by Edu789** [comment]
The PC-FX version of WiiMednafen, works well in the last version released, it has one or another problem of slowdown during gameplay and in the audio during videos.

**Comment by negativeExponent** [comment]
disable runahead

**Comment by Edu789** [comment]
> disable runahead

Where do you have this option?

**Comment by LibretroAdmin** [comment]
We cannot make any guarantees about performance on underpowered hardware like the Wii.

**Comment by saulfabregwiivc** [comment]
but would you add the "Frameskip" option to Beetle PC-FX?
