### ISSUE TITLE
Music Lags

### ISSUE THREAD

**Issue by Cebyo** [libretro/beetle-pcfx-libretro#78]
Hello,

I contact you because I have a problem to emulate pcfx games which is a console that I love on a 4 GB android box (H96 Max 3 x3) with the emuelec system. The problem is that the games work, but in the anime there are music lags in all the games. I would like to know if you could give me some advise me some parameters to help solve this.

**Comment by negativeExponent** [comment]
disable runahead, it the same, then system is too slow

**Comment by Cebyo** [comment]
It was disabled but thank for your help.
